export const contactObject = [
  { "name": "Alice Johnson", "email": "alice.johnson@example.com" },
  { "name": "Bob Smith", "email": "bob.smith@example.com" },
  { "name": "Charlie Brown", "email": "charlie.brown@example.com" },
  { "name": "David White", "email": "david.white@example.com" },
  { "name": "Emma Davis", "email": "emma.davis@example.com" },
  { "name": "Frank Harris", "email": "frank.harris@example.com" },
  { "name": "Grace Lee", "email": "grace.lee@example.com" },
  { "name": "Henry Wilson", "email": "henry.wilson@example.com" },
  { "name": "Ivy Martinez", "email": "ivy.martinez@example.com" },
  { "name": "Jack Taylor", "email": "jack.taylor@example.com" },
  { "name": "Kelly Anderson", "email": "kelly.anderson@example.com" },
  { "name": "Liam Thompson", "email": "liam.thompson@example.com" },
  { "name": "Mia Garcia", "email": "mia.garcia@example.com" },
  { "name": "Noah Robinson", "email": "noah.robinson@example.com" },
  { "name": "Olivia Clark", "email": "olivia.clark@example.com" },
  { "name": "Paul Walker", "email": "paul.walker@example.com" },
  { "name": "Quinn Foster", "email": "quinn.foster@example.com" },
  { "name": "Ryan Adams", "email": "ryan.adams@example.com" },
  { "name": "Sophia Carter", "email": "sophia.carter@example.com" },
  { "name": "Thomas Wright", "email": "thomas.wright@example.com" },
  { "name": "Uma Richards", "email": "uma.richards@example.com" },
  { "name": "Victor Lewis", "email": "victor.lewis@example.com" },
  { "name": "Wendy Hall", "email": "wendy.hall@example.com" },
  { "name": "Xavier Scott", "email": "xavier.scott@example.com" },
  { "name": "Yasmine Green", "email": "yasmine.green@example.com" },
  { "name": "Zane Harris", "email": "zane.harris@example.com" }
];
